name: Release
on: { push: { tags: [ 'v*' ] } }
permissions:
  deployments: write
  contents: write
jobs:
  publish-container:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5

      - name: Build container
        run: |
          docker run \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/workspace -w /workspace \
            buildpacksio/pack build \
            --builder heroku/builder:24 \
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Authenticate to ghcr.io
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Publish container
        shell: bash
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  create-release:
    runs-on: ubuntu-latest
    needs: [publish-container]
    steps:
      - name: Create GitHub release
        uses: actions/github-script@v8
        with:
          script: |
            const tag_name = context.ref.replace(/^refs\/tags\//, '');

            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag_name
              });

              console.log(`Release already exists for tag: ${release.data.name}`);
              return
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: `Release ${tag_name}`,
              tag_name: tag_name,
              draft: false,
              prerelease: false,
              generate_release_notes: true,
            });
            console.log(`Created release for tag: ${release.data.name}`);
